---
"Patrick Hochstenbach": "http://patrickhochstenbach.net/profile/card#me"
"Herbert Van de Sompel": "https://hvdsomp.info/#i"
"Ruben Dedecker": "https://pod.rubendedecker.be/profile/card#me"
"Ruben Verborgh": "https://ruben.verborgh.org/profile/#me"
"Miel Vander Sande": "https://be.linkedin.com/in/mielvds"
...